server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
  appenders:
    - type: console
      logFormat: "[%d{ISO8601}] %-5p [%t] %c: %m%n"