apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-remote-connect-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - nodePort: 30036
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mysql
  type: NodePort