apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  init.sql: |
{{ .Files.Get "files/texera_workflow_pod.sql" | cat (.Files.Get "files/texera_ddl.sql") | indent 4 }}