apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysqlPv.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    component: mysql
spec:
  capacity:
    storage: {{ .Values.mysqlPv.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: {{ .Values.mysqlPv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.mysqlPv.node }}