apiVersion: v1
kind: Service
metadata:
  name: texera-wf-brain-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.texeraWorkflowPodBrain.service.type }}
  selector:
    app: texera-wf-brain
  ports:
    - protocol: TCP
      port: {{ .Values.texeraWorkflowPodBrain.service.port }}
      targetPort: {{ .Values.texeraWorkflowPodBrain.service.port }}
      # if service type is set to NodePort, include nodePort attribute
      {{- if eq .Values.texeraWorkflowPodBrain.service.type "NodePort" }}
      nodePort: {{ .Values.texeraWorkflowPodBrain.service.nodePort }}
      {{- end }}