server:
  # modify applicationContextPath if you want the root path to be the name of the application
  # for example, set it to /twitter, then the url will become texera.ics.uci.edu:port/twitter
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
  requestLog:
    appenders: []
logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
  appenders:
    - type: file
      currentLogFilename: ../log/texera-workflow-compiling-service.log
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      archive: false
      timeZone: UTC
      logFormat: "[%date{ISO8601}] [%level] [%logger] [%thread] - %msg %n"
      bufferSize: 8KiB
      immediateFlush: true