{{- if .Values.ingressPaths.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Values.certManager.issuer }}
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: rke2-ingress-nginx
  rules:
    - host: {{ .Values.ingressPaths.hostname }}
      http:
        paths:
          {{- range .Values.ingressPaths.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingressPaths.hostname }}
      secretName: {{ .Values.tlsSecretName }}
{{- end }}
